version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: marriage-biodata-maker:latest
    ports:
      - "8080:80"
    restart: unless-stopped

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    command: ["npm", "start"]
